spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/posdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  sql:
    init:
      mode: never

  flyway:
    enabled: true
    locations: classpath:db/migration

  jwt:
    secret: 5XbK7LqN8rTfV2sWp9MzAeD4HyJ6UxCc
    expiration: 86400000